spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

security.token.secret.company=87d05c5b-19cf-47b4-bf8e-fe7f27d61211
security.token.secret.candidate=ee7ee83a-71cc-4067-98e2-f2c2a08adf8a