spring.application.name=gestao_vagas
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

security.token.secret.company=fccc10dd-84a5-4ef1-9165-41c4
security.token.secret.candidate=25b67bf6-fcda-4ce2-a651-4434568bd7dc