spring.application.name=gestao_vagas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

security.token.secret.company=${SECURITY_TOKEN_SECRET_COMPANY}
security.token.secret.candidate=${SECURITY_TOKEN_SECRET_CANDIDATE}

# sonar.token=${SONAR_TOKEN}
sonar.token=sqp_6e9bba97c8e084ed646bb72d8d039f1fe6eccebd

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true